name: Build and Test
on:
  push:
    branches: ["main"]

jobs:

  build:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Set up Go
      uses: actions/setup-go@v5.0.0
      with:
        go-version: ^1.21
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4.1.1

    - name: Build
      uses: go build -v ./...

